reload "autocommands"
reload "keymaps"
reload "plugins"
reload "options"
reload "whichkey"
-- reload "lsp"
-- reload "smoothie"
-- reload "harpoon"
-- reload "cybu"
-- reload "surround"
-- reload "bookmark"
-- reload "todo-comments"
-- reload "jaq"
-- reload "lab"
-- reload "git"
-- reload "zen-mode"
-- reload "inlay-hints"
-- reload "telescope"
-- reload "bqf"
-- reload "dial"
-- reload "numb"
-- reload "treesitter"
-- reload "neogit"
-- reload "colorizer"
-- reload "lualine"
-- reload "scrollbar"
